version: '3.7'

networks:
 laravel:

services:
 sql:
  image: mysql:5.7
  container_name : 'sql'
  tty: true
  restart : on-failure
  environment:
   MYSQL_DATABASE: ${DATABASE_NAME}
   MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
   MYSQL_PASSWORD: ${DATABASE_PASSWORD}
   MYSQL_USER: ${DATABASE_USERNAME}
   SERVICE_TAGS: dev
   SERVICE_NAME: mysql
  volumes:
   - ./sql-volume:/var/lib/mysql
  ports:
   - '3306:3306'
  networks:
   laravel:

 app:
  build:
   context: .
   dockerfile: Dockerfile
  image: 'laravelapp'
  container_name: app
  volumes :
   - ./src:/var/www/html/
  ports:
   - '8080:80'
  networks:
   laravel:
