version: '3.7'

networks:
 laravel:

services:
 mongo:
  image: 'mongo'
  container_name : 'mongo'
  restart: unless-stopped
  tty: true
  environment:
   - MONGO_INITDB_DATABASE=${DATABASE_NAME}
   - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
   - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
  volumes:
   - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
   - ./mongo-volume:/data/db
  ports:
   - '27017-27019:27017-27019'
  networks:
   laravel:

 app:
  build:
   context: .
   dockerfile: Dockerfile
  image: 'laravelapp'
  container_name: app
  volumes :
   - ./src:/var/www/html/
  ports:
   - '8080:80'
  networks:
   laravel:
