name: CI
 
on:
  - pull_request
  
jobs:
  tests:
      name: Tests
 
      runs-on: self-hosted
    
      services:
        sql:
         image: mysql:5.7
         env:
          MYSQL_DATABASE: ${DATABASE_NAME}
          MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
          MYSQL_PASSWORD: ${DATABASE_PASSWORD}
          MYSQL_USER: ${DATABASE_USERNAME}
         volumes:
          - /var/N4P/sql-volume:/var/lib/mysql
         ports:
          - '3309:3306'

        app:
         image: netw4ppl/website:latest
         volumes :
          - src:/var/www/html/
          - /etc/apache2/sites-available/docker_config.conf:/etc/apache2/sites-available/000-default.conf
         ports:
          - '7080:80'
          - '7443:443'
        redis:
         image: redis:6-alpine
         ports:
          - 6379:6379
      
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Prepare Laravel Application
          run: |
            cd src/
            cp .env.example .env
            php artisan key:generate
        - name: Migrate and seed
          run: |
            php artisan migrate --seed
        - name: run redis
          run: |
            php artisan redis:init
        - name: Run Testsuite
          run: php artisan test
          
        - name: Fix code coverage paths
          run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
          
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
