name: CI
 
on:
  - pull_request
  
jobs:
  tests:
      name: Tests
      runs-on: self-hosted
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Prepare Laravel Application
          run: |
            docker-compose up -d
            echo 'cp .env.example .env' | docker exec -i github-action-app /bin/bash
            echo 'composer update' | docker exec -i github-action-app /bin/bash
            echo 'php artisan key:generate > artisan.log' | docker exec -i github-action-app /bin/bash
            
        - name: Migrate and seed
          run: |
            echo 'php artisan migrate --seed > migrate.log' | docker exec -i github-action-app /bin/bash
            
        - name: run redis
          run: |
            php artisan redis:init
        - name: Run Testsuite
          run: php artisan test
          
        - name: Fix code coverage paths
          run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
          
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
