name: Generate and Publish Doxygen

on:
  push:
    branches:
      - main  # ou votre branche par défaut
  pull_request:
    branches:
      - main  # ou votre branche par défaut

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Si votre projet utilise des submodules
        
    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Doxygen Documentation
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        doxyfile-path: 'Doxyfile'  # Assurez-vous que le Doxyfile est à la racine du projet

    - name: Create /docs directory if not exists
      run: mkdir -p ${{ github.workspace }}/docs

    - name: Commit Documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Update documentation" -a || echo "No changes to commit"
      
    - name: Push Changes to Different Repository
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.REPO_PUSH}}  # Use a personal access token with permission to the target repo
        force: true
        branch: website-code-doc
        repository: org-SCAN/doc  # Replace with your username and the target repository
