name: Improve Issue
on:
  issues:
    types: [opened]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Issue Processor
        uses: lduf/issueGPT@0.1
        with:
          ai_model: 'gpt-4-1106-preview'
          max_tokens: '1000'
          OPENAI_API_KEY: ${{ secrets.GPT_KEY }}
          
